Repository jeffsieu/coma-dash, pull requests merged in 2020-05, with the labels that each got.

#107 Dash: Check if ray intersection with the enemy exists
  Scripts/Weapon/DashSkill.cs
Labels: bug, category: controls

#110 Optimise floor generation in MapLoader
  Coma Dash.csproj
  Maps/basic.data
  Maps/basic2.data
  Maps/basic3.data
  Maps/basic4.data
  Maps/map.data
  Scenes/MainLevel.tscn
  Scripts/Generator/Door.cs
  Scripts/Generator/Floor.cs
  Scripts/Generator/MapLoader.cs
  Scripts/Generator/Room.cs
Labels: category: level, enhancement

#122 HealthEntity: Only update healthbars when Health > 0
  Scripts/HealthEntity.cs
Labels: bug

#121 Projectile: Destroy object once it collides with something
  Scripts/Generator/MapLoader.cs
  Scripts/Generator/Test.cs
  Scripts/Generator/Wall.cs
  Scripts/Projectile.cs
Labels: category: attack

#117 Add Apple and Pencil
  Assets/apple.glb
  Assets/apple.glb.import
  Assets/pencil.glb
  Assets/pencil.glb.import
  Coma Dash.csproj
  Scenes/Assets/EnemyApple.tscn
  Scenes/Assets/EnemyPencil.tscn
  Scenes/MainLevel.tscn
  Scripts/Enemy/EnemyPencil.cs
  Scripts/Generator/MapLoader.cs
Labels: category: enemies
